name: FIT4002 DASDD Nginx CI

on: [push, pull_request, workflow_dispatch]

jobs:
  publish:
    name: Publish Images to Docker Hub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push NGINX Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: imuh0001/fit4002-dasdd-nginx:latest
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    needs:
      - publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*' '**/node_modules/*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "fit4002-dasdd"
          environment_name: "fit4002-dasdd-env"
          version_label: 1
          region: "ap-southeast-2"
          deployment_package: deploy.zip
          use_existing_version_if_available: true
